services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    environment:
      - 'LOG_START_BUILD=1'
      - 'LOG_COMPLETE_BUILD=1'
      - 'DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'DATASOURCE_USERNAME=postgres'
      - 'DATASOURCE_PASSWORD=secret'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy